#pragma once
/* -copyright-
*/
#include "../src/Pixmaps/flake0.xpm"
#include "../src/Pixmaps/flake10.xpm"
#include "../src/Pixmaps/flake11.xpm"
#include "../src/Pixmaps/flake12.xpm"
#include "../src/Pixmaps/flake13.xpm"
#include "../src/Pixmaps/flake14.xpm"
#include "../src/Pixmaps/flake15.xpm"
#include "../src/Pixmaps/flake16.xpm"
#include "../src/Pixmaps/flake17.xpm"
#include "../src/Pixmaps/flake18.xpm"
#include "../src/Pixmaps/flake19.xpm"
#include "../src/Pixmaps/flake1.xpm"
#include "../src/Pixmaps/flake20.xpm"
#include "../src/Pixmaps/flake21.xpm"
#include "../src/Pixmaps/flake22.xpm"
#include "../src/Pixmaps/flake23.xpm"
#include "../src/Pixmaps/flake24.xpm"
#include "../src/Pixmaps/flake25.xpm"
#include "../src/Pixmaps/flake26.xpm"
#include "../src/Pixmaps/flake27.xpm"
#include "../src/Pixmaps/flake28.xpm"
#include "../src/Pixmaps/flake29.xpm"
#include "../src/Pixmaps/flake2.xpm"
#include "../src/Pixmaps/flake30.xpm"
#include "../src/Pixmaps/flake31.xpm"
#include "../src/Pixmaps/flake32.xpm"
#include "../src/Pixmaps/flake33.xpm"
#include "../src/Pixmaps/flake34.xpm"
#include "../src/Pixmaps/flake35.xpm"
#include "../src/Pixmaps/flake36.xpm"
#include "../src/Pixmaps/flake37.xpm"
#include "../src/Pixmaps/flake38.xpm"
#include "../src/Pixmaps/flake39.xpm"
#include "../src/Pixmaps/flake3.xpm"
#include "../src/Pixmaps/flake40.xpm"
#include "../src/Pixmaps/flake4.xpm"
#include "../src/Pixmaps/flake5.xpm"
#include "../src/Pixmaps/flake6.xpm"
#include "../src/Pixmaps/flake7.xpm"
#include "../src/Pixmaps/flake8.xpm"
#include "../src/Pixmaps/flake9.xpm"
#define SNOW_ALL \
SNOW(0) \
SNOW(1) \
SNOW(2) \
SNOW(3) \
SNOW(4) \
SNOW(5) \
SNOW(6) \
SNOW(7) \
SNOW(8) \
SNOW(9) \
SNOW(10) \
SNOW(11) \
SNOW(12) \
SNOW(13) \
SNOW(14) \
SNOW(15) \
SNOW(16) \
SNOW(17) \
SNOW(18) \
SNOW(19) \
SNOW(20) \
SNOW(21) \
SNOW(22) \
SNOW(23) \
SNOW(24) \
SNOW(25) \
SNOW(26) \
SNOW(27) \
SNOW(28) \
SNOW(29) \
SNOW(30) \
SNOW(31) \
SNOW(32) \
SNOW(33) \
SNOW(34) \
SNOW(35) \
SNOW(36) \
SNOW(37) \
SNOW(38) \
SNOW(39) \
SNOW(40) \

