#!/bin/bash
# creates directory for upload
# version numbers for upstream releases:
newversion=`./getversion`
#oldversion=2.0.19
oldversion=3.0.7
curdir=`pwd`
dist=sid
tar=$curdir/../versions/xsnow-$newversion.tar.gz
uploaddir=$curdir/../upload/upload-$newversion
./maketar || exit 1
echo removing $uploaddir ...
mkdir -p $uploaddir
sudo chown -R willem.willem $uploaddir
rm -rf $uploaddir
mkdir -p $uploaddir
cd $uploaddir || exit 1
cp -v $tar . || exit 1
#apt source xsnow || exit 1
cp -r $curdir/../xsnow-debian/debian . || exit 1
sudo bash `which pbuilder` --execute --bindmounts $PWD \
   --configfile ~root/pbuilderrc.$dist  \
   -- $curdir/pbuilderscript $PWD $oldversion $newversion|| exit 1
sudo chown -R willem.willem $uploaddir
rm -r xsnow-$oldversion
rm    xsnow_$oldversion-*.debian.tar.[gx]z
rm    xsnow_$oldversion-*.dsc
rm    xsnow_$oldversion.orig.tar.gz
rm -r xsnow-$newversion
rm -r xsnow-$newversion.orig
debsign -k8D232D69D0889859B1E7732ADC4874F4A7D3496F *.changes
echo to check: dput -s mentors $uploaddir/*.changes
echo to upload: dput mentors $uploaddir/*.changes
echo "$0 done"
