#!/bin/bash
ulimit -c unlimited
rm -f core
clear
#M32=-m32
#export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
if true; then
   export CC=gcc-10 CXX=g++-10
   export CFLAGS="$M32 -Wextra   -Wint-conversion -Wpedantic -Wall -O2 -g -DNO_USE_BITS"
   export CXXFLAGS="$M32 -Wextra                  -Wpedantic -Wall -O2 -g -DNO_USE_BITS"
   export LDFLAGS="$M32"
else
   export CC=g++-10 CXX=g++-10
   export CFLAGS='-Wextra -Wzero-as-null-pointer-constant -Wpedantic -Wall -O2 -g -DNO_USE_BITS' 
   export CXXFLAGS='-Wextra -Wzero-as-null-pointer-constant -Wpedantic -Wall -O2 -g -DNO_USE_BITS' 
fi
if [ ! -e Makefile ] ; then
   ./configure && make clean
fi
make   -j && src/xsnow -noisy  --g-fatal-warnings "$@"
#make -j  && GDK_SYNCHRONIZE=1 GTK_DEBUG=interactive src/xsnow #--g-fatal-warnings
#make -j  && GTK_DEBUG=interactive src/xsnow --g-fatal-warnings

