#!/bin/bash
ulimit -c unlimited
rm -f core
reset
if true; then
   export CC=gcc-10 CXX=g++-10
   export CFLAGS='-Wextra -Wint-conversion -Wpedantic -Wall -O0 -g -DNO_USE_BITS'
else
   export CC=g++-10 CXX=g++-10
   export CFLAGS='-Wextra -Wzero-as-null-pointer-constant -Wpedantic -Wall -O0 -g -DNO_USE_BITS' 
fi
if [ ! -e Makefile ] ; then
   ./configure && make clean
fi
make   && src/xsnow -noisy  --g-fatal-warnings
#make -j  && GDK_SYNCHRONIZE=1 GTK_DEBUG=interactive src/xsnow #--g-fatal-warnings
#make -j  && GTK_DEBUG=interactive src/xsnow --g-fatal-warnings

