# -copyright-
#-# 
#-# xsnow: let it snow on your desktop
#-# Copyright (C) 1984,1988,1990,1993-1995,2000-2001 Rick Jansen
#-#               2019,2020 Willem Vermin
#-# 
#-# This program is free software: you can redistribute it and/or modify
#-# it under the terms of the GNU General Public License as published by
#-# the Free Software Foundation, either version 3 of the License, or
#-# (at your option) any later version.
#-# 
#-# This program is distributed in the hope that it will be useful,
#-# but WITHOUT ANY WARRANTY; without even the implied warranty of
#-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#-# GNU General Public License for more details.
#-# 
#-# You should have received a copy of the GNU General Public License
#-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-# 
EXTRA_DIST = \
make.inc \
README \
AltSanta1.xpm \
AltSanta2.xpm \
AltSanta3.xpm \
AltSanta4.xpm \
AltSantaRudolf1.xpm \
AltSantaRudolf2.xpm \
AltSantaRudolf3.xpm \
AltSantaRudolf4.xpm \
BigSanta1.xpm \
BigSanta2.xpm \
BigSanta3.xpm \
BigSanta4.xpm \
BigSanta81.xpm \
BigSanta82.xpm \
BigSanta83.xpm \
BigSanta84.xpm \
BigSantaRudolf1.xpm \
BigSantaRudolf2.xpm \
BigSantaRudolf3.xpm \
BigSantaRudolf4.xpm \
BigSantaRudolf81.xpm \
BigSantaRudolf82.xpm \
BigSantaRudolf83.xpm \
BigSantaRudolf84.xpm \
bird1.xpm \
bird2.xpm \
bird3.xpm \
bird4.xpm \
bird5.xpm \
bird6.xpm \
bird7.xpm \
bird8.xpm \
birdd1.xpm \
birdd2.xpm \
birdd3.xpm \
birdd4.xpm \
birdd5.xpm \
birdd6.xpm \
birdd7.xpm \
birdd8.xpm \
birdl1.xpm \
birdl2.xpm \
birdl3.xpm \
birdl4.xpm \
birdl5.xpm \
birdl6.xpm \
birdl7.xpm \
birdl8.xpm \
eland.xpm \
huis4.xpm \
MediumSanta1.xpm \
MediumSanta2.xpm \
MediumSanta3.xpm \
MediumSanta4.xpm \
MediumSantaRudolf1.xpm \
MediumSantaRudolf2.xpm \
MediumSantaRudolf3.xpm \
MediumSantaRudolf4.xpm \
polarbear.png \
polarbear.xpm \
RegularSanta1.xpm \
RegularSanta2.xpm \
RegularSanta3.xpm \
RegularSanta4.xpm \
RegularSantaRudolf1.xpm \
RegularSantaRudolf2.xpm \
RegularSantaRudolf3.xpm \
RegularSantaRudolf4.xpm \
rendier.xpm \
snow00.xbm \
snow00.xpm \
snow01.xbm \
snow01.xpm \
snow02.xbm \
snow02.xpm \
snow03.xbm \
snow03.xpm \
snow04.xbm \
snow04.xpm \
snow05.xbm \
snow05.xpm \
snow06.xbm \
snow06.xpm \
snow07.xbm \
snow07.xpm \
snow08.xbm \
snow08.xpm \
snow09.xbm \
snow09.xpm \
snow10.xbm \
snow10.xpm \
snow11.xbm \
snow11.xpm \
snow12.xbm \
snow12.xpm \
snow13.xbm \
snow13.xpm \
snow14.xbm \
snow14.xpm \
snow15.xbm \
snow15.xpm \
snow16.xbm \
snow16.xpm \
snow17.xbm \
snow17.xpm \
snow18.xbm \
snow18.xpm \
snow19.xbm \
snow19.xpm \
snow20.xbm \
snow20.xpm \
snow21.xbm \
snow21.xpm \
snow22.xbm \
snow22.xpm \
snow23.xbm \
snow23.xpm \
snow24.xbm \
snow24.xpm \
snow25.xbm \
snow25.xpm \
snow26.xbm \
snow26.xpm \
snow27.xbm \
snow27.xpm \
snow28.xbm \
snow28.xpm \
snow29.xbm \
snow29.xpm \
snow30.xbm \
snow30.xpm \
snow31.xbm \
snow31.xpm \
snow32.xbm \
snow32.xpm \
snow33.xbm \
snow33.xpm \
snow34.xbm \
snow34.xpm \
snow35.xbm \
snow35.xpm \
snow36.xbm \
snow36.xpm \
snow37.xbm \
snow37.xpm \
snow38.xbm \
snow38.xpm \
snow39.xbm \
snow39.xpm \
snow40.xbm \
snow40.xpm \
snowtree.xpm \
star.xbm \
tannenbaum.xpm \
tree-1_100px.xpm \
tree.xpm \
xsnow41x30.xpm \
xsnow64x64.xpm \
xsnow.jpg \
xsnow.png \
xsnow.svg \
xsnow.xpm 
